const RETO60_API_URL="https://grznkkkmehxclqkniobt.supabase.co/functions/v1/reto60-api";
const R60_GAME_ID="reto60";
function reto60GuestId(){let id=localStorage.getItem("reto60_guest_id");if(!id){id=crypto.randomUUID?crypto.randomUUID():"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==="x"?r:(r&3|8);return v.toString(16)});localStorage.setItem("reto60_guest_id",id)}return id;}
function isTelegramPlayer(){return !!(window.Telegram?.WebApp?.initData);}
async function reto60Cloud(action,payload={}){const initData=window.Telegram?.WebApp?.initData||"",headers={"Content-Type":"application/json"};if(initData)headers["x-telegram-init-data"]=initData;else headers["x-guest-id"]=reto60GuestId();try{const response=await fetch(RETO60_API_URL,{method:"POST",headers,body:JSON.stringify({action,game_id:R60_GAME_ID,...payload})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP_${response.status}`);return {ok:true,...data};}catch(error){console.warn("Reto 60 cloud:",error);return {ok:false,error:String(error?.message||error)};}}
function reto60NormalizeIdentity(r){if(!r?.player)return r;const accountId=r.r60_account_id||r.player.r60_account_id||null;const coins=Number(r.r60_coins??r.wallet?.coins??0)||0;return {...r,r60:{account_id:accountId,coins,game_id:R60_GAME_ID},player:{...r.player,r60_account_id:accountId,r60_coins:coins}};}
let reto60GuestNamePromise=null;
function reto60AskGuestName(){if(reto60GuestNamePromise)return reto60GuestNamePromise;reto60GuestNamePromise=new Promise(resolve=>{const old=document.getElementById("reto60GuestOnboarding");if(old)old.remove();const overlay=document.createElement("div");overlay.id="reto60GuestOnboarding";overlay.style.cssText="position:fixed;inset:0;z-index:99999;background:rgba(4,7,18,.96);display:flex;align-items:center;justify-content:center;padding:22px;font-family:Arial,sans-serif";overlay.innerHTML='<div style="width:100%;max-width:430px;background:#151a35;border:1px solid #343c73;border-radius:24px;padding:28px 22px;text-align:center;color:#fff;box-shadow:0 18px 60px rgba(0,0,0,.45)"><div style="font-size:42px;margin-bottom:8px">👋</div><h2 style="margin:4px 0 8px;font-size:28px">¡Bienvenido a Reto 60!</h2><p style="color:#b8bdd2;line-height:1.45;margin:0 0 20px">Antes de jugar, elige tu nombre o apodo para guardar tus puntos y competir en el ranking global.</p><input id="reto60GuestNameInput" maxlength="40" autocomplete="nickname" placeholder="Tu nombre o apodo" style="width:100%;border:1px solid #3a437d;background:#0e132b;color:#fff;border-radius:14px;padding:16px;font-size:18px;outline:none;text-align:center"><div id="reto60GuestNameError" style="min-height:22px;color:#ff7b7b;font-size:13px;margin-top:8px"></div><button id="reto60GuestNameSave" style="width:100%;border:0;border-radius:16px;padding:17px;margin-top:4px;font-size:17px;font-weight:bold;background:#ffb800;color:#111;cursor:pointer">CONTINUAR ⚡</button></div>';document.body.appendChild(overlay);const input=overlay.querySelector("#reto60GuestNameInput"),button=overlay.querySelector("#reto60GuestNameSave"),error=overlay.querySelector("#reto60GuestNameError");const save=async()=>{const name=input.value.trim();if(name.length<2){error.textContent="Escribe al menos 2 caracteres.";input.focus();return;}button.disabled=true;button.textContent="GUARDANDO...";error.textContent="";const r=await setCloudDisplayName(name);if(r.ok){localStorage.setItem("reto60_display_name",name);overlay.remove();reto60GuestNamePromise=null;resolve(r.player||{display_name:name});return;}error.textContent="No pudimos guardar el nombre. Intenta otra vez.";button.disabled=false;button.textContent="CONTINUAR ⚡";};button.onclick=save;input.addEventListener("keydown",e=>{if(e.key==="Enter")save();});setTimeout(()=>input.focus(),120);});return reto60GuestNamePromise;}
async function ensureReto60GuestProfile(){if(isTelegramPlayer())return true;const saved=(localStorage.getItem("reto60_display_name")||"").trim();if(saved.length>=2)return true;await reto60AskGuestName();return (localStorage.getItem("reto60_display_name")||"").trim().length>=2;}
document.addEventListener("click",async e=>{if(isTelegramPlayer())return;const button=e.target.closest&&e.target.closest("button");if(!button||button.dataset.reto60ProfilePassed==="1")return;const startsChallenge=button.id==="acceptChallenge"||button.textContent.includes("JUGAR RETO 60")||button.classList.contains("category");if(!startsChallenge)return;const saved=(localStorage.getItem("reto60_display_name")||"").trim();if(saved.length>=2)return;e.preventDefault();e.stopImmediatePropagation();const ok=await ensureReto60GuestProfile();if(ok){button.dataset.reto60ProfilePassed="1";button.click();delete button.dataset.reto60ProfilePassed;}},true);
async function syncCloudPlayer(){let r=reto60NormalizeIdentity(await reto60Cloud("sync_player"));if(!r.ok||isTelegramPlayer()||!r.player)return r;const saved=(localStorage.getItem("reto60_display_name")||"").trim();if(!saved&&(r.player.display_name==="Invitado"||!r.player.display_name)){const player=await reto60AskGuestName();return reto60NormalizeIdentity({...r,player});}return r;}
async function setCloudDisplayName(display_name){return reto60NormalizeIdentity(await reto60Cloud("set_display_name",{display_name}));}
async function recordCloudMatch({category,score,seed,mode}){const result=await reto60Cloud("record_match",{category,score,seed,mode});reto60ApplyProgress(Number(score)||0);return result;}
async function getCloudLeaderboard(){return reto60Cloud("leaderboard");}
async function createCloudChallenge({opponent_id,category,seed,challenger_score=0}){return reto60Cloud("create_challenge",{opponent_id,category,seed,challenger_score});}
async function getPendingChallenges(){return reto60Cloud("pending_challenges");}
async function respondCloudChallenge(challenge_id,decision){return reto60Cloud("respond_challenge",{challenge_id,decision});}
async function completeCloudChallenge(challenge_id,score){return reto60Cloud("complete_challenge",{challenge_id,score});}
async function getDuelHistory(){return reto60Cloud("duel_history");}

/* Reto 60 progression: XP, levels, personal best and daily streak UI. */
function reto60LevelFromXp(xp){return Math.floor(Math.sqrt(Math.max(0,xp)/100))+1;}
function reto60XpForLevel(level){return Math.pow(Math.max(0,level-1),2)*100;}
function reto60Progress(){const xp=Number(localStorage.getItem("reto60_xp")||0),best=Number(localStorage.getItem("reto60_best")||0),level=reto60LevelFromXp(xp),base=reto60XpForLevel(level),next=reto60XpForLevel(level+1);return {xp,best,level,base,next,pct:Math.max(0,Math.min(100,((xp-base)/(next-base))*100||0))};}
let reto60LastGain=0,reto60NewBest=false,reto60LeveledUp=false;
function reto60ApplyProgress(points){const before=reto60Progress(),gain=Math.max(10,Math.max(0,points)),newXp=before.xp+gain,oldBest=before.best,newBest=Math.max(oldBest,points);localStorage.setItem("reto60_xp",String(newXp));localStorage.setItem("reto60_best",String(newBest));const after=reto60Progress();reto60LastGain=gain;reto60NewBest=points>oldBest;reto60LeveledUp=after.level>before.level;setTimeout(()=>{reto60RenderProgress();reto60RenderResultProgress();},0);}
function reto60RenderProgress(){const home=document.getElementById("home");if(!home)return;let box=document.getElementById("reto60ProgressBox");if(!box){box=document.createElement("div");box.id="reto60ProgressBox";box.className="panel";box.style.cssText="padding:18px 20px;text-align:left";const stats=home.querySelector(".stats");if(stats)stats.insertAdjacentElement("afterend",box);else home.prepend(box);}const p=reto60Progress(),streak=Number(localStorage.getItem("reto60streak")||0);box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div><div style="font-size:12px;color:#aaa">PROGRESO</div><div style="font-size:22px;font-weight:900;color:#ffb800">⚡ NIVEL ${p.level}</div></div><div style="text-align:right"><div style="font-size:13px;color:#fff">🏆 Récord ${p.best}</div><div style="font-size:12px;color:#aaa">🔥 Racha ${streak} días</div></div></div><div style="height:10px;background:#252c58;border-radius:20px;overflow:hidden;margin-top:13px"><div style="height:100%;width:${p.pct}%;background:#ffb800;border-radius:20px"></div></div><div style="display:flex;justify-content:space-between;color:#aaa;font-size:11px;margin-top:6px"><span>${p.xp} XP</span><span>${p.next-p.xp} XP para nivel ${p.level+1}</span></div>`;}
function reto60RenderResultProgress(){const result=document.getElementById("result");if(!result||result.classList.contains("hidden"))return;const panel=result.querySelector(".panel");if(!panel)return;let box=document.getElementById("reto60ResultProgress");if(!box){box=document.createElement("div");box.id="reto60ResultProgress";const versus=document.getElementById("versusResult");if(versus)versus.insertAdjacentElement("beforebegin",box);else panel.appendChild(box);}const p=reto60Progress();box.style.cssText="margin:18px 0;padding:15px;background:#1d2347;border-radius:16px";box.innerHTML=`<div style="font-size:20px;font-weight:900;color:#ffb800">+${reto60LastGain} XP</div>${reto60NewBest?'<div style="margin-top:6px;font-weight:bold">🏆 ¡NUEVO RÉCORD PERSONAL!</div>':''}${reto60LeveledUp?`<div style="margin-top:6px;font-weight:bold">⚡ ¡SUBISTE AL NIVEL ${p.level}!</div>`:''}<div style="font-size:13px;color:#aaa;margin-top:7px">Nivel ${p.level} · Récord ${p.best} puntos</div><div style="height:8px;background:#252c58;border-radius:20px;overflow:hidden;margin-top:9px"><div style="height:100%;width:${p.pct}%;background:#ffb800"></div></div>`;}
function reto60InstallProgress(){reto60RenderProgress();const result=document.getElementById("result");if(result)new MutationObserver(()=>{if(!result.classList.contains("hidden"))setTimeout(reto60RenderResultProgress,20);}).observe(result,{attributes:true,attributeFilter:["class"]});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",reto60InstallProgress);else setTimeout(reto60InstallProgress,0);
