const RETO60_API_URL="https://grznkkkmehxclqkniobt.supabase.co/functions/v1/reto60-api";
function reto60GuestId(){let id=localStorage.getItem("reto60_guest_id");if(!id){id=crypto.randomUUID?crypto.randomUUID():"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==="x"?r:(r&3|8);return v.toString(16)});localStorage.setItem("reto60_guest_id",id)}return id;}
function isTelegramPlayer(){return !!(window.Telegram?.WebApp?.initData);}
async function reto60Cloud(action,payload={}){const initData=window.Telegram?.WebApp?.initData||"",headers={"Content-Type":"application/json"};if(initData)headers["x-telegram-init-data"]=initData;else headers["x-guest-id"]=reto60GuestId();try{const response=await fetch(RETO60_API_URL,{method:"POST",headers,body:JSON.stringify({action,...payload})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP_${response.status}`);return {ok:true,...data};}catch(error){console.warn("Reto 60 cloud:",error);return {ok:false,error:String(error?.message||error)};}}
let reto60GuestNamePromise=null;
function reto60AskGuestName(){if(reto60GuestNamePromise)return reto60GuestNamePromise;reto60GuestNamePromise=new Promise(resolve=>{const old=document.getElementById("reto60GuestOnboarding");if(old)old.remove();const overlay=document.createElement("div");overlay.id="reto60GuestOnboarding";overlay.style.cssText="position:fixed;inset:0;z-index:99999;background:rgba(4,7,18,.96);display:flex;align-items:center;justify-content:center;padding:22px;font-family:Arial,sans-serif";overlay.innerHTML='<div style="width:100%;max-width:430px;background:#151a35;border:1px solid #343c73;border-radius:24px;padding:28px 22px;text-align:center;color:#fff;box-shadow:0 18px 60px rgba(0,0,0,.45)"><div style="font-size:42px;margin-bottom:8px">👋</div><h2 style="margin:4px 0 8px;font-size:28px">¡Bienvenido a Reto 60!</h2><p style="color:#b8bdd2;line-height:1.45;margin:0 0 20px">Antes de jugar, elige tu nombre o apodo para guardar tus puntos y competir en el ranking global.</p><input id="reto60GuestNameInput" maxlength="40" autocomplete="nickname" placeholder="Tu nombre o apodo" style="width:100%;border:1px solid #3a437d;background:#0e132b;color:#fff;border-radius:14px;padding:16px;font-size:18px;outline:none;text-align:center"><div id="reto60GuestNameError" style="min-height:22px;color:#ff7b7b;font-size:13px;margin-top:8px"></div><button id="reto60GuestNameSave" style="width:100%;border:0;border-radius:16px;padding:17px;margin-top:4px;font-size:17px;font-weight:bold;background:#ffb800;color:#111;cursor:pointer">CONTINUAR ⚡</button></div>';document.body.appendChild(overlay);const input=overlay.querySelector("#reto60GuestNameInput"),button=overlay.querySelector("#reto60GuestNameSave"),error=overlay.querySelector("#reto60GuestNameError");const save=async()=>{const name=input.value.trim();if(name.length<2){error.textContent="Escribe al menos 2 caracteres.";input.focus();return;}button.disabled=true;button.textContent="GUARDANDO...";error.textContent="";const r=await setCloudDisplayName(name);if(r.ok){localStorage.setItem("reto60_display_name",name);overlay.remove();reto60GuestNamePromise=null;resolve(r.player||{display_name:name});return;}error.textContent="No pudimos guardar el nombre. Intenta otra vez.";button.disabled=false;button.textContent="CONTINUAR ⚡";};button.onclick=save;input.addEventListener("keydown",e=>{if(e.key==="Enter")save();});setTimeout(()=>input.focus(),120);});return reto60GuestNamePromise;}
async function ensureReto60GuestProfile(){if(isTelegramPlayer())return true;const saved=(localStorage.getItem("reto60_display_name")||"").trim();if(saved.length>=2)return true;await reto60AskGuestName();return (localStorage.getItem("reto60_display_name")||"").trim().length>=2;}
/* Important: embedded browsers can race past startup onboarding. Intercept every gameplay click in capture phase, before index.html starts the timer. */
document.addEventListener("click",async e=>{if(isTelegramPlayer())return;const button=e.target.closest&&e.target.closest("button");if(!button||button.dataset.reto60ProfilePassed==="1")return;const startsChallenge=button.id==="acceptChallenge"||button.textContent.includes("JUGAR RETO 60")||button.classList.contains("category");if(!startsChallenge)return;const saved=(localStorage.getItem("reto60_display_name")||"").trim();if(saved.length>=2)return;e.preventDefault();e.stopImmediatePropagation();const ok=await ensureReto60GuestProfile();if(ok){button.dataset.reto60ProfilePassed="1";button.click();delete button.dataset.reto60ProfilePassed;}},true);
async function syncCloudPlayer(){const r=await reto60Cloud("sync_player");if(!r.ok||isTelegramPlayer()||!r.player)return r;const saved=(localStorage.getItem("reto60_display_name")||"").trim();if(!saved&&(r.player.display_name==="Invitado"||!r.player.display_name)){const player=await reto60AskGuestName();return {...r,player};}return r;}
async function setCloudDisplayName(display_name){return reto60Cloud("set_display_name",{display_name});}
async function recordCloudMatch({category,score,seed,mode}){return reto60Cloud("record_match",{category,score,seed,mode});}
async function getCloudLeaderboard(){return reto60Cloud("leaderboard");}
async function createCloudChallenge({opponent_id,category,seed,challenger_score=0}){return reto60Cloud("create_challenge",{opponent_id,category,seed,challenger_score});}
async function getPendingChallenges(){return reto60Cloud("pending_challenges");}
async function respondCloudChallenge(challenge_id,decision){return reto60Cloud("respond_challenge",{challenge_id,decision});}
async function completeCloudChallenge(challenge_id,score){return reto60Cloud("complete_challenge",{challenge_id,score});}
async function getDuelHistory(){return reto60Cloud("duel_history");}
