/* Reto 60 rewards: R60 Coins + daily missions + daily chest (virtual, non-cash) */
(function(){
 const K={coins:'reto60_r60_coins',day:'reto60_rewards_day',games:'reto60_daily_games',best:'reto60_daily_best',cats:'reto60_daily_categories',chest:'reto60_daily_chest',bonus:'reto60_daily_bonus'};
 const today=()=>new Date().toISOString().slice(0,10),num=k=>Number(localStorage.getItem(k)||0),set=(k,v)=>localStorage.setItem(k,String(v));
 function reset(){if(localStorage.getItem(K.day)===today())return;localStorage.setItem(K.day,today());set(K.games,0);set(K.best,0);localStorage.setItem(K.cats,'[]');localStorage.removeItem(K.chest);localStorage.removeItem(K.bonus);}
 function coins(){return num(K.coins)} function add(n){set(K.coins,coins()+n);render();return coins();}
 function missions(){reset();const games=num(K.games),best=num(K.best),cats=JSON.parse(localStorage.getItem(K.cats)||'[]');return [
  {id:'play3',icon:'🎮',name:'Juega 3 partidas',now:Math.min(games,3),goal:3,reward:8,ok:games>=3},
  {id:'score60',icon:'🏆',name:'Consigue 60 puntos',now:Math.min(best,60),goal:60,reward:6,ok:best>=60},
  {id:'categories2',icon:'🎯',name:'Juega 2 categorías',now:Math.min(cats.length,2),goal:2,reward:6,ok:cats.length>=2}
 ];}
 function claimed(){return JSON.parse(localStorage.getItem('reto60_claimed_'+today())||'[]')} function claim(id){const m=missions().find(x=>x.id===id),c=claimed();if(!m?.ok||c.includes(id))return;c.push(id);localStorage.setItem('reto60_claimed_'+today(),JSON.stringify(c));add(m.reward);toast(`🪙 +${m.reward} R60`,`Misión completada: ${m.name}`);render();}
 function chest(){reset();if(num(K.games)<1){toast('🔒 Cofre bloqueado','Completa tu primera partida del día.');return}if(localStorage.getItem(K.chest)){toast('🎁 Cofre abierto','Vuelve mañana para conseguir otro.');return}const rewards=[5,6,7,8,10,12],r=rewards[Math.floor(Math.random()*rewards.length)];localStorage.setItem(K.chest,String(r));add(r);toast(`🎁 ¡+${r} R60!`,'Premio del cofre diario');render();}
 function toast(title,text){document.getElementById('r60RewardToast')?.remove();const o=document.createElement('div');o.id='r60RewardToast';o.style.cssText='position:fixed;inset:0;z-index:100020;background:rgba(4,7,18,.92);display:flex;align-items:center;justify-content:center;padding:22px;color:white;font-family:Arial';o.innerHTML=`<div style="max-width:390px;width:100%;text-align:center;background:#151a35;border:2px solid #ffb800;border-radius:25px;padding:28px"><div style="font-size:31px;font-weight:900;color:#ffb800">${title}</div><p style="color:#bbb">${text}</p><button id="r60ToastClose" style="background:#ffb800;color:#111">CONTINUAR</button></div>`;document.body.appendChild(o);o.querySelector('#r60ToastClose').onclick=()=>o.remove();}
 function render(){reset();const box=document.getElementById('r60Rewards');if(!box)return;const c=claimed(),ms=missions();box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><div><b>🪙 R60 COINS</b><div class="small">Moneda virtual de recompensas</div></div><div style="font-size:25px;font-weight:900;color:#ffb800">${coins()}</div></div><button id="r60Chest" class="play">${localStorage.getItem(K.chest)?'🎁 COFRE DE HOY ABIERTO':num(K.games)>=1?'🎁 ABRIR COFRE DIARIO':'🔒 COFRE · JUEGA 1 PARTIDA'}</button><h3 style="margin-bottom:5px">🎯 Misiones de hoy</h3>${ms.map(m=>`<div style="background:#1d2347;border-radius:14px;padding:12px;margin-top:8px;text-align:left"><div style="display:flex;justify-content:space-between;gap:8px"><b>${m.icon} ${m.name}</b><span>${m.now}/${m.goal}</span></div><div style="height:7px;background:#252c58;border-radius:9px;overflow:hidden;margin:8px 0"><div style="height:100%;width:${Math.min(100,m.now/m.goal*100)}%;background:#ffb800"></div></div>${m.ok&&!c.includes(m.id)?`<button class="mini r60Claim" data-id="${m.id}">RECLAMAR +${m.reward} R60</button>`:c.includes(m.id)?'<span class="small">✅ Reclamada</span>':`<span class="small">Premio: +${m.reward} R60</span>`}</div>`).join('')}`;box.querySelector('#r60Chest').onclick=chest;box.querySelectorAll('.r60Claim').forEach(b=>b.onclick=()=>claim(b.dataset.id));}
 function install(){const home=document.getElementById('home');if(!home||document.getElementById('r60Rewards'))return;const box=document.createElement('div');box.id='r60Rewards';box.className='panel';const profile=document.getElementById('reto60ProfileButton');if(profile)profile.insertAdjacentElement('afterend',box);else home.querySelector('.stats')?.insertAdjacentElement('afterend',box);render();let was=true;const result=document.getElementById('result');if(result)new MutationObserver(()=>{const hidden=result.classList.contains('hidden');if(was&&!hidden){reset();set(K.games,num(K.games)+1);set(K.best,Math.max(num(K.best),Number(window.score||0)));let cats=JSON.parse(localStorage.getItem(K.cats)||'[]'),cat=window.currentCategory||'all';if(!cats.includes(cat)){cats.push(cat);localStorage.setItem(K.cats,JSON.stringify(cats))}setTimeout(render,150)}was=hidden}).observe(result,{attributes:true,attributeFilter:['class']});}
 window.R60Rewards={coins,add,missions,render};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,120));else setTimeout(install,120);
})();