/* Reto 60 Store preview: no real payments or coin deductions yet */
(function(){
 const PRODUCTS=[
  {id:'time10',icon:'⏱️',name:'+10 segundos',kind:'Potenciador',price:'Premium',desc:'Añade 10 segundos a una partida cuando esté activado.'},
  {id:'fox',icon:'🦊',name:'Zorro R60',kind:'Mascota',price:'Premium',desc:'Mascota de puntuación. Su habilidad se activará en una fase posterior.'},
  {id:'owl',icon:'🦉',name:'Búho R60',kind:'Mascota',price:'Próximamente',desc:'Mascota enfocada en conocimiento y ayudas especiales.'}
 ];
 function close(){document.getElementById('r60Store')?.remove()}
 function open(){close();const o=document.createElement('div');o.id='r60Store';o.style.cssText='position:fixed;inset:0;z-index:100030;background:linear-gradient(160deg,#080b18,#151a38);overflow:auto;color:white;font-family:Arial;padding:22px';o.innerHTML=`<div style="max-width:500px;margin:auto"><button id="r60StoreClose" style="width:auto;background:#252c58;color:white;padding:12px 18px">← VOLVER</button><div style="text-align:center;margin:22px 0"><div style="font-size:34px;font-weight:900">🛒 TIENDA <span style="color:#ffb800">RETO 60</span></div><div style="color:#aaa;margin-top:7px">Mascotas, potenciadores y objetos especiales</div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:18px"><button class="r60Tab" data-tab="shop" style="background:#ffb800;color:#111">🛒 TIENDA</button><button class="r60Tab" data-tab="inventory" style="background:#252c58;color:white">🎒 INVENTARIO</button></div><div id="r60StoreBody"></div><div style="text-align:center;color:#777;font-size:12px;padding:18px">Vista previa · Los pagos reales todavía no están activados.</div></div>`;document.body.appendChild(o);o.querySelector('#r60StoreClose').onclick=close;o.querySelectorAll('.r60Tab').forEach(b=>b.onclick=()=>renderTab(b.dataset.tab));renderTab('shop');}
 function renderTab(tab){const body=document.getElementById('r60StoreBody');if(!body)return;document.querySelectorAll('.r60Tab').forEach(b=>{const on=b.dataset.tab===tab;b.style.background=on?'#ffb800':'#252c58';b.style.color=on?'#111':'white'});if(tab==='inventory'){body.innerHTML=`<div style="background:#151a35;border:1px solid #292f5c;border-radius:22px;padding:25px;text-align:center"><div style="font-size:48px">🎒</div><h2>Tu inventario</h2><p style="color:#aaa">Aquí aparecerán tus mascotas, potenciadores y objetos comprados.</p><button disabled style="opacity:.55;background:#252c58;color:white">INVENTARIO EN PREPARACIÓN</button></div>`;return}body.innerHTML=`<div style="background:#151a35;border:1px solid #292f5c;border-radius:22px;padding:20px;margin-bottom:14px"><h2 style="margin-top:0">💎 Premium</h2><p style="color:#aaa">Productos de pago. En esta versión solo puedes verlos; no se realizará ningún cobro.</p></div>${PRODUCTS.map(p=>`<div style="background:#151a35;border:1px solid #292f5c;border-radius:22px;padding:18px;margin-bottom:12px"><div style="display:flex;gap:14px;align-items:center"><div style="font-size:42px">${p.icon}</div><div style="flex:1"><div style="font-size:12px;color:#ffb800;font-weight:bold">${p.kind.toUpperCase()}</div><h2 style="margin:4px 0">${p.name}</h2><div style="color:#aaa;font-size:13px">${p.desc}</div></div></div><div style="display:flex;align-items:center;justify-content:space-between;margin-top:14px"><b>${p.price}</b><button class="r60PreviewBuy" data-id="${p.id}" style="width:auto;margin:0;background:#252c58;color:white;padding:11px 14px">VER OBJETO</button></div></div>`).join('')}`;body.querySelectorAll('.r60PreviewBuy').forEach(b=>b.onclick=()=>preview(b.dataset.id));}
 function preview(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const old=document.getElementById('r60StorePreview');old?.remove();const d=document.createElement('div');d.id='r60StorePreview';d.style.cssText='position:fixed;inset:0;z-index:100040;background:rgba(4,7,18,.94);display:flex;align-items:center;justify-content:center;padding:22px';d.innerHTML=`<div style="max-width:390px;width:100%;background:#151a35;border:2px solid #ffb800;border-radius:25px;padding:28px;text-align:center;color:white"><div style="font-size:64px">${p.icon}</div><h2>${p.name}</h2><p style="color:#aaa">${p.desc}</p><b style="color:#ffb800">${p.price}</b><button id="r60PreviewClose" style="background:#ffb800;color:#111">ENTENDIDO</button><div style="color:#777;font-size:11px;margin-top:10px">Compra desactivada durante las pruebas.</div></div>`;document.body.appendChild(d);d.querySelector('#r60PreviewClose').onclick=()=>d.remove();}
 function install(){if(document.getElementById('r60StoreButton'))return true;const rewards=document.getElementById('r60Rewards');if(!rewards)return false;const b=document.createElement('button');b.id='r60StoreButton';b.textContent='🛒 TIENDA · MASCOTAS Y POTENCIADORES';b.style.cssText='background:#252c58;color:white;margin-top:12px';b.onclick=open;rewards.insertAdjacentElement('afterend',b);return true;}
 function boot(){if(install())return;let n=0;const t=setInterval(()=>{n++;if(install()||n>30)clearInterval(t)},150)}
 window.R60Store={open,close,install,products:PRODUCTS};boot();
})();